### PR TITLE
remove trailing .

### PR DESCRIPTION
**Pull request by trel**

### CODE REVIEW

**Comment by acaos** [comment]
I actually prefer to keep this as a personal habit of mine - but please let me know if it's causing you an issue and I will merge this PR.

**Comment by trel** [comment]
no worries - certainly not an issue.

what's the reason/upside for the personal preference?    i haven't seen it before.

**Comment by acaos** [comment]
Habit from working with a number of editors that make inserting at the end painful, mostly. Honestly, few other people do it, and it is a strange personal quirk of mine, so I will merge this to keep the level of surprise down. Thank you!

**Comment by trel** [comment]
Fair enough.  Thanks.

**Pull request merged**
